jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - run: docker build .
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: orb-test
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push